version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/webhooks
      - REDIS_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webhooks
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A webhook_service.celery_app worker --loglevel=info
    depends_on:
      - api
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/webhooks
      - REDIS_BROKER_URL=redis://redis:6379/0

volumes:
  pgdata: